           name: Playwright Tests

           on:
             push:
               branches: [ master, main ]
             workflow_dispatch:
           env:
             API_KEY_VALUE : test
           jobs:
             test:
               runs-on: ubuntu-latest

               steps:
                 - name: Checkout repository
                   uses: actions/checkout@v4

                 - name: Setup Node.js
                   uses: actions/setup-node@v4
                   with:
                     node-version: '20'

                 - name: Install dependencies
                   run: npm install

                 - name: Install Playwright browsers
                   run: npx playwright install --with-deps

                 - name: Run Playwright tests
                   run: npx playwright test
                   continue-on-error: true
                 - name: 🧰 Install Allure CLI
                   run: |
                     wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
                     tar -xvzf allure-2.27.0.tgz
                     sudo mv allure-2.27.0 /opt/allure
                     sudo ln -s /opt/allure/bin/allure /usr/bin/allure
                     allure --version
                 - name: 🧾 Generate Allure report
                   run: |
                     allure generate allure-results --clean -o allure-report   
                 - name: 📤 Upload Allure report artifact
                   uses: actions/upload-artifact@v4
                   with:
                     name: allure-report
                     path: allure-report
           